using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AlphaScopeServer.Models.Entities
{
    /// <summary>
    /// One-time short-TTL code generated by the plugin's Settings UI. The user pastes the
    /// code on the web's /me/link page while Discord-signed-in to merge their plugin-side
    /// ApplicationUser with their web-side identity. Row is deleted on successful redemption.
    /// </summary>
    [Table("AccountLinkCodes")]
    public class AccountLinkCode
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public int ApplicationUserId { get; set; }

        [Required]
        [MaxLength(16)]
        public string Code { get; set; } = string.Empty;

        [Required]
        public DateTime ExpiresAt { get; set; }

        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        [ForeignKey(nameof(ApplicationUserId))]
        public virtual ApplicationUser ApplicationUser { get; set; } = null!;
    }
}
