// <auto-generated />
using System;
using MemoriaServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MemoriaServer.Migrations
{
    [DbContext(typeof(MemoriaDbContext))]
    [Migration("20260426041716_WidenPlayerAccountIdToBigint")]
    partial class WidenPlayerAccountIdToBigint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MemoriaServer.Models.Entities.AccountLinkCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("AccountLinkCodes");
                });

            modelBuilder.Entity("MemoriaServer.Models.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("AppRoleId")
                        .HasColumnType("integer");

                    b.Property<string>("BaseUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DiscordUserId")
                        .HasColumnType("bigint");

                    b.Property<int>("FetchedPlayerInfoCount")
                        .HasColumnType("integer");

                    b.Property<int?>("GameAccountId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("GuildMembershipCheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsGuildMember")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSyncedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("PrimaryCharacterLocalContentId")
                        .HasColumnType("bigint");

                    b.Property<int>("SearchedNamesCount")
                        .HasColumnType("integer");

                    b.Property<int>("TotalContributions")
                        .HasColumnType("integer");

                    b.Property<int>("UploadedPlayerInfoCount")
                        .HasColumnType("integer");

                    b.Property<int>("UploadedPlayersCount")
                        .HasColumnType("integer");

                    b.Property<int>("UploadedRetainerInfoCount")
                        .HasColumnType("integer");

                    b.Property<int>("UploadedRetainersCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApiKey")
                        .IsUnique();

                    b.HasIndex("DiscordUserId")
                        .IsUnique()
                        .HasFilter("\"DiscordUserId\" IS NOT NULL");

                    b.HasIndex("GameAccountId")
                        .IsUnique()
                        .HasFilter("\"GameAccountId\" IS NOT NULL");

                    b.HasIndex("PrimaryCharacterLocalContentId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MemoriaServer.Models.Entities.ClaimAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("PlayerLocalContentId")
                        .HasColumnType("bigint");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("PlayerLocalContentId");

                    b.HasIndex("UserId", "PlayerLocalContentId")
                        .IsUnique();

                    b.ToTable("ClaimAttempts");
                });

            modelBuilder.Entity("MemoriaServer.Models.Entities.Player", b =>
                {
                    b.Property<long>("LocalContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("LocalContentId"));

                    b.Property<long?>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<string>("AvatarLink")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("ClaimVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ClaimedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte?>("CurrentJobId")
                        .HasColumnType("smallint");

                    b.Property<short?>("CurrentJobLevel")
                        .HasColumnType("smallint");

                    b.Property<short?>("CurrentWorldId")
                        .HasColumnType("smallint");

                    b.Property<bool>("HideAlts")
                        .HasColumnType("boolean");

                    b.Property<bool>("HideEncounters")
                        .HasColumnType("boolean");

                    b.Property<bool>("HideEntirely")
                        .HasColumnType("boolean");

                    b.Property<bool>("HideInSearch")
                        .HasColumnType("boolean");

                    b.Property<short?>("HomeWorldId")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastJobDataUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastMinionsDataUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastMountsDataUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastScannedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LodestoneJobData")
                        .HasColumnType("text");

                    b.Property<string>("LodestoneMinionsData")
                        .HasColumnType("text");

                    b.Property<string>("LodestoneMountsData")
                        .HasColumnType("text");

                    b.Property<byte?>("MainJobId")
                        .HasColumnType("smallint");

                    b.Property<short?>("MainJobLevel")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PlayerPos")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<short?>("TerritoryId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LocalContentId");

                    b.HasIndex("AccountId");

                    b.HasIndex("ClaimedByUserId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CurrentWorldId");

                    b.HasIndex("HideEntirely");

                    b.HasIndex("HomeWorldId");

                    b.HasIndex("Name");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("MemoriaServer.Models.Entities.PlayerCustomizationHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte?>("BodyType")
                        .HasColumnType("smallint");

                    b.Property<byte?>("BustSize")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte?>("EyeShape")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Face")
                        .HasColumnType("smallint");

                    b.Property<byte?>("GenderRace")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Height")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Jaw")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Mouth")
                        .HasColumnType("smallint");

                    b.Property<byte?>("MuscleMass")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Nose")
                        .HasColumnType("smallint");

                    b.Property<long>("PlayerLocalContentId")
                        .HasColumnType("bigint");

                    b.Property<byte?>("SkinColor")
                        .HasColumnType("smallint");

                    b.Property<bool?>("SmallIris")
                        .HasColumnType("boolean");

                    b.Property<byte?>("TailShape")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PlayerLocalContentId");

                    b.ToTable("PlayerCustomizationHistory");
                });

            modelBuilder.Entity("MemoriaServer.Models.Entities.PlayerLodestone", b =>
                {
                    b.Property<long>("PlayerLocalContentId")
                        .HasColumnType("bigint");

                    b.Property<string>("AvatarLink")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("CharacterCreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LodestoneId")
                        .HasColumnType("integer");

                    b.HasKey("PlayerLocalContentId");

                    b.HasIndex("LodestoneId")
                        .IsUnique();

                    b.ToTable("PlayerLodestone");
                });

            modelBuilder.Entity("MemoriaServer.Models.Entities.PlayerNameHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("PlayerLocalContentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PlayerLocalContentId");

                    b.ToTable("PlayerNameHistory");
                });

            modelBuilder.Entity("MemoriaServer.Models.Entities.PlayerProfileVisit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("PlayerLocalContentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("VisitedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VisitorId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerLocalContentId");

                    b.HasIndex("VisitedAt");

                    b.ToTable("PlayerProfileVisits");
                });

            modelBuilder.Entity("MemoriaServer.Models.Entities.PlayerTerritoryHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("PlayerLocalContentId")
                        .HasColumnType("bigint");

                    b.Property<string>("PlayerPos")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<short?>("TerritoryId")
                        .HasColumnType("smallint");

                    b.Property<short?>("WorldId")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("FirstSeenAt");

                    b.HasIndex("LastSeenAt");

                    b.HasIndex("PlayerLocalContentId");

                    b.ToTable("PlayerTerritoryHistory");
                });

            modelBuilder.Entity("MemoriaServer.Models.Entities.PlayerWorldHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("PlayerLocalContentId")
                        .HasColumnType("bigint");

                    b.Property<short>("WorldId")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PlayerLocalContentId");

                    b.ToTable("PlayerWorldHistory");
                });

            modelBuilder.Entity("MemoriaServer.Models.Entities.TakedownRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("NameSlug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ResolutionNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ResolvedByUserId")
                        .HasColumnType("integer");

                    b.Property<long?>("ResolvedPlayerLocalContentId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubmitterIpHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("WorldSlug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("ResolvedByUserId");

                    b.HasIndex("ResolvedPlayerLocalContentId");

                    b.HasIndex("Status");

                    b.HasIndex("SubmittedAt");

                    b.HasIndex("SubmitterIpHash");

                    b.HasIndex("WorldSlug", "NameSlug");

                    b.ToTable("TakedownRequests");
                });

            modelBuilder.Entity("MemoriaServer.Models.Entities.TerritoryName", b =>
                {
                    b.Property<short>("TerritoryId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("TerritoryId");

                    b.ToTable("TerritoryNames");
                });

            modelBuilder.Entity("MemoriaServer.Models.Entities.UserCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarLink")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("HideAltCharacters")
                        .HasColumnType("boolean");

                    b.Property<bool>("HideCustomizations")
                        .HasColumnType("boolean");

                    b.Property<bool>("HideFullProfile")
                        .HasColumnType("boolean");

                    b.Property<bool>("HideInSearchResults")
                        .HasColumnType("boolean");

                    b.Property<bool>("HideRetainersInfo")
                        .HasColumnType("boolean");

                    b.Property<bool>("HideTerritoryInfo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastProfileVisitDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LocalContentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ProfileTotalVisitCount")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LocalContentId");

                    b.HasIndex("UserId");

                    b.ToTable("UserCharacters");
                });

            modelBuilder.Entity("MemoriaServer.Models.Entities.UserScannedPlayer", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<long>("PlayerLocalContentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastScannedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "PlayerLocalContentId");

                    b.HasIndex("PlayerLocalContentId");

                    b.HasIndex("UserId", "LastScannedAt");

                    b.ToTable("UserScannedPlayers");
                });

            modelBuilder.Entity("MemoriaServer.Models.Entities.AccountLinkCode", b =>
                {
                    b.HasOne("MemoriaServer.Models.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("MemoriaServer.Models.Entities.ClaimAttempt", b =>
                {
                    b.HasOne("MemoriaServer.Models.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerLocalContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MemoriaServer.Models.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MemoriaServer.Models.Entities.Player", b =>
                {
                    b.HasOne("MemoriaServer.Models.Entities.ApplicationUser", "ClaimedByUser")
                        .WithMany()
                        .HasForeignKey("ClaimedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ClaimedByUser");
                });

            modelBuilder.Entity("MemoriaServer.Models.Entities.PlayerCustomizationHistory", b =>
                {
                    b.HasOne("MemoriaServer.Models.Entities.Player", "Player")
                        .WithMany("CustomizationHistory")
                        .HasForeignKey("PlayerLocalContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("MemoriaServer.Models.Entities.PlayerLodestone", b =>
                {
                    b.HasOne("MemoriaServer.Models.Entities.Player", "Player")
                        .WithOne("Lodestone")
                        .HasForeignKey("MemoriaServer.Models.Entities.PlayerLodestone", "PlayerLocalContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("MemoriaServer.Models.Entities.PlayerNameHistory", b =>
                {
                    b.HasOne("MemoriaServer.Models.Entities.Player", "Player")
                        .WithMany("NameHistory")
                        .HasForeignKey("PlayerLocalContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("MemoriaServer.Models.Entities.PlayerProfileVisit", b =>
                {
                    b.HasOne("MemoriaServer.Models.Entities.Player", "Player")
                        .WithMany("ProfileVisits")
                        .HasForeignKey("PlayerLocalContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("MemoriaServer.Models.Entities.PlayerTerritoryHistory", b =>
                {
                    b.HasOne("MemoriaServer.Models.Entities.Player", "Player")
                        .WithMany("TerritoryHistory")
                        .HasForeignKey("PlayerLocalContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("MemoriaServer.Models.Entities.PlayerWorldHistory", b =>
                {
                    b.HasOne("MemoriaServer.Models.Entities.Player", "Player")
                        .WithMany("WorldHistory")
                        .HasForeignKey("PlayerLocalContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("MemoriaServer.Models.Entities.TakedownRequest", b =>
                {
                    b.HasOne("MemoriaServer.Models.Entities.ApplicationUser", "ResolvedByUser")
                        .WithMany()
                        .HasForeignKey("ResolvedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MemoriaServer.Models.Entities.Player", "ResolvedPlayer")
                        .WithMany()
                        .HasForeignKey("ResolvedPlayerLocalContentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ResolvedByUser");

                    b.Navigation("ResolvedPlayer");
                });

            modelBuilder.Entity("MemoriaServer.Models.Entities.UserCharacter", b =>
                {
                    b.HasOne("MemoriaServer.Models.Entities.ApplicationUser", "User")
                        .WithMany("Characters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MemoriaServer.Models.Entities.UserScannedPlayer", b =>
                {
                    b.HasOne("MemoriaServer.Models.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerLocalContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MemoriaServer.Models.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MemoriaServer.Models.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("MemoriaServer.Models.Entities.Player", b =>
                {
                    b.Navigation("CustomizationHistory");

                    b.Navigation("Lodestone");

                    b.Navigation("NameHistory");

                    b.Navigation("ProfileVisits");

                    b.Navigation("TerritoryHistory");

                    b.Navigation("WorldHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
