// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using AlphaScope.Database;

#nullable disable

namespace AlphaScope.Database.Migrations
{
    [DbContext(typeof(RetainerTrackContext))]
    partial class RetainerTrackContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("RetainerTrack.Database.Player", b =>
            {
                b.Property<ulong>("LocalContentId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<ulong?>("AccountId")
                    .HasColumnType("INTEGER");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("TEXT");

                b.HasKey("LocalContentId");

                b.ToTable("Players");
            });

#pragma warning restore 612, 618
        }
    }
}

