// <auto-generated />
using System;
using AlphaScope.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlphaScope.Database.Migrations
{
    [DbContext(typeof(RetainerTrackContext))]
    partial class RetainerTrackContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("AlphaScope.Database.Player", b =>
                {
                    b.Property<ulong>("LocalContentId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarLink")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<byte?>("CurrentJobId")
                        .HasColumnType("INTEGER");

                    b.Property<short?>("CurrentJobLevel")
                        .HasColumnType("INTEGER");

                    b.Property<ushort?>("CurrentWorldId")
                        .HasColumnType("INTEGER");

                    b.Property<ushort?>("HomeWorldId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastScannedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("LocalContentId");

                    b.ToTable("Players");
                });
#pragma warning restore 612, 618
        }
    }
}