// <auto-generated />
using System;
using AlphaScopeServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlphaScopeServer.Migrations
{
    [DbContext(typeof(AlphaScopeDbContext))]
    partial class AlphaScopeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlphaScopeServer.Models.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("AppRoleId")
                        .HasColumnType("integer");

                    b.Property<string>("BaseUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FetchedPlayerInfoCount")
                        .HasColumnType("integer");

                    b.Property<int>("GameAccountId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSyncedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("PrimaryCharacterLocalContentId")
                        .HasColumnType("bigint");

                    b.Property<int>("SearchedNamesCount")
                        .HasColumnType("integer");

                    b.Property<int>("UploadedPlayerInfoCount")
                        .HasColumnType("integer");

                    b.Property<int>("UploadedPlayersCount")
                        .HasColumnType("integer");

                    b.Property<int>("UploadedRetainerInfoCount")
                        .HasColumnType("integer");

                    b.Property<int>("UploadedRetainersCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApiKey")
                        .IsUnique();

                    b.HasIndex("GameAccountId")
                        .IsUnique();

                    b.HasIndex("PrimaryCharacterLocalContentId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AlphaScopeServer.Models.Entities.Player", b =>
                {
                    b.Property<long>("LocalContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("LocalContentId"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("integer");

                    b.Property<string>("AvatarLink")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte?>("CurrentJobId")
                        .HasColumnType("smallint");

                    b.Property<short?>("CurrentJobLevel")
                        .HasColumnType("smallint");

                    b.Property<short?>("CurrentWorldId")
                        .HasColumnType("smallint");

                    b.Property<bool>("HideInSearch")
                        .HasColumnType("boolean");

                    b.Property<short?>("HomeWorldId")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastJobDataUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastMinionsDataUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastMountsDataUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastScannedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LodestoneJobData")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("LodestoneMinionsData")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<string>("LodestoneMountsData")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<byte?>("MainJobId")
                        .HasColumnType("smallint");

                    b.Property<short?>("MainJobLevel")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PlayerPos")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<short?>("TerritoryId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LocalContentId");

                    b.HasIndex("AccountId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CurrentWorldId");

                    b.HasIndex("HomeWorldId");

                    b.HasIndex("Name");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("AlphaScopeServer.Models.Entities.PlayerCustomizationHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte?>("BodyType")
                        .HasColumnType("smallint");

                    b.Property<byte?>("BustSize")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte?>("EyeShape")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Face")
                        .HasColumnType("smallint");

                    b.Property<byte?>("GenderRace")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Height")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Jaw")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Mouth")
                        .HasColumnType("smallint");

                    b.Property<byte?>("MuscleMass")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Nose")
                        .HasColumnType("smallint");

                    b.Property<long>("PlayerLocalContentId")
                        .HasColumnType("bigint");

                    b.Property<byte?>("SkinColor")
                        .HasColumnType("smallint");

                    b.Property<bool?>("SmallIris")
                        .HasColumnType("boolean");

                    b.Property<byte?>("TailShape")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PlayerLocalContentId");

                    b.ToTable("PlayerCustomizationHistory");
                });

            modelBuilder.Entity("AlphaScopeServer.Models.Entities.PlayerLodestone", b =>
                {
                    b.Property<long>("PlayerLocalContentId")
                        .HasColumnType("bigint");

                    b.Property<string>("AvatarLink")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("CharacterCreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LodestoneId")
                        .HasColumnType("integer");

                    b.HasKey("PlayerLocalContentId");

                    b.HasIndex("LodestoneId")
                        .IsUnique();

                    b.ToTable("PlayerLodestone");
                });

            modelBuilder.Entity("AlphaScopeServer.Models.Entities.PlayerNameHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("PlayerLocalContentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PlayerLocalContentId");

                    b.ToTable("PlayerNameHistory");
                });

            modelBuilder.Entity("AlphaScopeServer.Models.Entities.PlayerProfileVisit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("PlayerLocalContentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("VisitedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VisitorId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerLocalContentId");

                    b.HasIndex("VisitedAt");

                    b.ToTable("PlayerProfileVisits");
                });

            modelBuilder.Entity("AlphaScopeServer.Models.Entities.PlayerTerritoryHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("PlayerLocalContentId")
                        .HasColumnType("bigint");

                    b.Property<string>("PlayerPos")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<short?>("TerritoryId")
                        .HasColumnType("smallint");

                    b.Property<short?>("WorldId")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("FirstSeenAt");

                    b.HasIndex("LastSeenAt");

                    b.HasIndex("PlayerLocalContentId");

                    b.ToTable("PlayerTerritoryHistory");
                });

            modelBuilder.Entity("AlphaScopeServer.Models.Entities.PlayerWorldHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("PlayerLocalContentId")
                        .HasColumnType("bigint");

                    b.Property<short>("WorldId")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PlayerLocalContentId");

                    b.ToTable("PlayerWorldHistory");
                });

            modelBuilder.Entity("AlphaScopeServer.Models.Entities.UserCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarLink")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("HideAltCharacters")
                        .HasColumnType("boolean");

                    b.Property<bool>("HideCustomizations")
                        .HasColumnType("boolean");

                    b.Property<bool>("HideFullProfile")
                        .HasColumnType("boolean");

                    b.Property<bool>("HideInSearchResults")
                        .HasColumnType("boolean");

                    b.Property<bool>("HideRetainersInfo")
                        .HasColumnType("boolean");

                    b.Property<bool>("HideTerritoryInfo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastProfileVisitDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LocalContentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ProfileTotalVisitCount")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LocalContentId");

                    b.HasIndex("UserId");

                    b.ToTable("UserCharacters");
                });

            modelBuilder.Entity("AlphaScopeServer.Models.Entities.UserLodestoneCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarLink")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("LodestoneId")
                        .HasColumnType("integer");

                    b.Property<string>("NameAndWorld")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LodestoneId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("UserLodestoneCharacters");
                });

            modelBuilder.Entity("AlphaScopeServer.Models.Entities.PlayerCustomizationHistory", b =>
                {
                    b.HasOne("AlphaScopeServer.Models.Entities.Player", "Player")
                        .WithMany("CustomizationHistory")
                        .HasForeignKey("PlayerLocalContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("AlphaScopeServer.Models.Entities.PlayerLodestone", b =>
                {
                    b.HasOne("AlphaScopeServer.Models.Entities.Player", "Player")
                        .WithOne("Lodestone")
                        .HasForeignKey("AlphaScopeServer.Models.Entities.PlayerLodestone", "PlayerLocalContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("AlphaScopeServer.Models.Entities.PlayerNameHistory", b =>
                {
                    b.HasOne("AlphaScopeServer.Models.Entities.Player", "Player")
                        .WithMany("NameHistory")
                        .HasForeignKey("PlayerLocalContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("AlphaScopeServer.Models.Entities.PlayerProfileVisit", b =>
                {
                    b.HasOne("AlphaScopeServer.Models.Entities.Player", "Player")
                        .WithMany("ProfileVisits")
                        .HasForeignKey("PlayerLocalContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("AlphaScopeServer.Models.Entities.PlayerTerritoryHistory", b =>
                {
                    b.HasOne("AlphaScopeServer.Models.Entities.Player", "Player")
                        .WithMany("TerritoryHistory")
                        .HasForeignKey("PlayerLocalContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("AlphaScopeServer.Models.Entities.PlayerWorldHistory", b =>
                {
                    b.HasOne("AlphaScopeServer.Models.Entities.Player", "Player")
                        .WithMany("WorldHistory")
                        .HasForeignKey("PlayerLocalContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("AlphaScopeServer.Models.Entities.UserCharacter", b =>
                {
                    b.HasOne("AlphaScopeServer.Models.Entities.ApplicationUser", "User")
                        .WithMany("Characters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AlphaScopeServer.Models.Entities.UserLodestoneCharacter", b =>
                {
                    b.HasOne("AlphaScopeServer.Models.Entities.ApplicationUser", "User")
                        .WithMany("LodestoneCharacters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AlphaScopeServer.Models.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("LodestoneCharacters");
                });

            modelBuilder.Entity("AlphaScopeServer.Models.Entities.Player", b =>
                {
                    b.Navigation("CustomizationHistory");

                    b.Navigation("Lodestone");

                    b.Navigation("NameHistory");

                    b.Navigation("ProfileVisits");

                    b.Navigation("TerritoryHistory");

                    b.Navigation("WorldHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
